# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_no', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('book_type', models.CharField(choices=[('Programming', 'Programming'), ('Computer', 'Computer'), ('Math', 'Math'), ('Economics', 'Economics'), ('Accounting', 'Accounting'), ('Others', 'Others')], max_length=15)),
                ('edition', models.IntegerField()),
                ('no_of_books', models.IntegerField()),
            ],
        ),
    ]
