# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Computer', 'Computer'), ('Math', 'Math'), ('Economics', 'Economics'), ('Accounting', 'Accounting'), ('Others', 'Others')], default='Others', max_length=15),
        ),
    ]
