# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 20:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_auto_20170324_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_isbn_no', models.CharField(max_length=100)),
                ('issue_book_name', models.CharField(max_length=100)),
                ('issue_date', models.DateTimeField(default=datetime.datetime(2017, 3, 26, 13, 8, 52, 245000))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
