# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 03:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170326_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 26, 20, 53, 32, 158000)),
        ),
    ]
