# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 04:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20170326_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='due_fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 26, 21, 43, 29, 109000)),
        ),
    ]
