# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 03:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20170326_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.DateField(default=datetime.date(2017, 4, 11)),
        ),
    ]
