# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 00:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20170411_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='return_date',
            field=models.DateField(default=datetime.date(2017, 4, 27)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.DateField(default=datetime.date(2017, 4, 12)),
        ),
    ]
